version: "3.8"
services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: StrongPass1
      discovery.type: single-node
    networks:
      - elk_stack
  logstash:
    build:
      context: logstash/
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:8.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
    command: metricbeat -e -E output.elasticsearch.hosts=["elasticsearch:9200"]
  filebeat:
    build:
      context: filebeat/
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: filebeat -e -strict.perms=false
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
      - logstash
networks:
  elk_stack:
    driver: bridge
volumes:
  elasticsearch: